# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contact_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
